name: 'Build and test'

runs:
    using: "composite"

    steps:
      - name: Create build directory
        run: mkdir build
        shell: bash

      - name: Configure
        run: |
          cmake -LA .. \
           -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
           -DOSMIUM_INCLUDE_DIR=${GITHUB_WORKSPACE}/../libosmium/include \
           -DPROTOZERO_INCLUDE_DIR=${GITHUB_WORKSPACE}/../protozero/include \
           -DERROR_ON_WARNINGS=ON
        shell: bash
        working-directory: build

      - name: Build
        run: make VERBOSE=1
        shell: bash
        working-directory: build

      - name: Test
        run: ctest --output-on-failure
        shell: bash
        working-directory: build

