name: CMake

runs:
    using: composite

    steps:
      - name: Create build directory
        run: mkdir build
        shell: bash

      - name: Configure
        run: |
          cmake -LA .. \
           -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
           -DERROR_ON_WARNINGS=ON
        shell: bash
        working-directory: build

