name: CI

on: [ push, pull_request ]

jobs:
  ubuntu20-clang-dev:
    runs-on: ubuntu-20.04
    env:
      CC: clang
      CXX: clang++
      BUILD_TYPE: Dev
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  ubuntu22-clang-dev:
    runs-on: ubuntu-22.04
    env:
      CC: clang
      CXX: clang++
      BUILD_TYPE: Dev
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  ubuntu24-clang-dev:
    runs-on: ubuntu-24.04
    env:
      CC: clang
      CXX: clang++
      BUILD_TYPE: Dev
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  ubuntu24-clang-san-dev:
    runs-on: ubuntu-24.04
    env:
      CC: clang
      CXX: clang++
      BUILD_TYPE: Dev
      CXXFLAGS: -fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer
      LDFLAGS: -fsanitize=address,undefined
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  ubuntu24-clang-release:
    runs-on: ubuntu-24.04
    env:
      CC: clang
      CXX: clang++
      BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  ubuntu20-gcc-dev:
    runs-on: ubuntu-20.04
    env:
      CC: gcc-9
      CXX: g++-9
      BUILD_TYPE: Dev
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  ubuntu22-gcc-dev:
    runs-on: ubuntu-22.04
    env:
      CC: gcc-9
      CXX: g++-9
      BUILD_TYPE: Dev
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  ubuntu24-gcc-dev:
    runs-on: ubuntu-24.04
    env:
      CC: gcc
      CXX: g++
      BUILD_TYPE: Dev
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  ubuntu24-gcc-release:
    runs-on: ubuntu-24.04
    env:
      CC: gcc
      CXX: g++
      BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

